version: "3.9"
services:
  dns-dmz:
    image: "internetsystemsconsortium/bind9:9.16"
    hostname: "dns"
    domainname: "woodytoys.domaineprojetadmin.ovh"
    volumes: 
      - "./dns/public/named.conf:/etc/bind/named.conf"
      - "./dns/public/zones/:/etc/bind/zones/"
      - "./dns/public/named.conf.local:/etc/bind/named.conf.local"
      - "./dns/public/named.conf.options:/etc/bind/named.conf.options"
    ports: 
      - "53:53"
      - "53:53/udp"
    networks: 
      dmz: 
        ipv4_address: "172.18.3.2"
  voip-dmz:
    image: "andrius/asterisk"
    hostname: "voip"
    domainname: "woodytoys.domaineprojetadmin.ovh"
    networks: 
      dmz: 
        ipv4_address: "172.18.3.3"
  web-dmz:
    image: "php:7.2-apache"
    hostname: "web"
    domainname: "woodytoys.domaineprojetadmin.ovh"
    volumes: 
      - "./web/conf/sites-available/:/etc/apache2/sites-enabled"
      - "./web/www/:/var/www/woodtoys.com/"
    ports: 
      - "80:80"
    networks: 
      dmz: 
        ipv4_address: "172.18.3.4"
      internal-servers:
  smtp-dmz: 
    image: "mailserver/docker-mailserver"
    hostname: "smtp"
    domainname: "woodytoys.domaineprojetadmin.ovh"
    networks: 
      dmz: 
        ipv4_address: "172.18.3.5"
  dns-internal:
    image: "internetsystemsconsortium/bind9:9.16"
    networks: 
      internal-servers: 
        ipv4_address: "172.18.1.3"
  resolver-internal:
    image: "internetsystemsconsortium/bind9:9.16"
    networks: 
      internal-servers: 
        ipv4_address: "172.18.1.2"
  #ERP-internal:
  db-internal: 
    image: "mariadb"
    networks: 
      internal-servers: 
        ipv4_address: "172.18.1.4"
    
  pc-direction:
    image: "ubuntu"
    networks: 
      internal-computers: 
        ipv4_address: "192.168.0.2"
      internal-servers:
  pc-secretariat:
    image: "ubuntu"
    networks: 
      internal-computers: 
        ipv4_address: "192.168.0.3"
      internal-servers:
networks:
  dmz:
    ipam:
      config:
        - subnet: "172.18.3.0/24"
  internal-servers:
    ipam:
      config:
        - subnet: "172.18.1.0/24"
  internal-computers:
    ipam:
      config:
        - subnet: "192.168.0.0/16"